In [1]:
import requests
from IPython.core.display import HTML
HTML(f"""
<style>
@import "https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css";
</style>
""")

# Linear Algebra using Python and Numpy
This exercise introduces fundamental linear algebra operations in Numpy and how to use them to solve linear systems of equations. The goal is to familiarise yourself with the concepts of linear algebra and how to use them in Numpy. The following topics will be covered:
- Performing matrix operations (elementwise operations, transpose, multiplication, inverse).
- Properties of matrix multiplication and inverse.
- Representing linear equations in matrix form.
- Solving linear equations using the matrix inverse.


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#diff">Task 1: Elementwise difference</a>
            </li>
            <li>
            <a href="#mul_prop">Task 2: Multiplication properties</a>
            </li>
            <li>
            <a href="#elem_mul">Task 3: Elementwise multiplication</a>
            </li>
            <li>
            <a href="#inverses">Task 4: Inverses</a>
            </li>
            <li>
            <a href="#inverse_prop">Task 5: Inverse properties</a>
            </li>
            <li>
            <a href="#determinant">Task 6: The determinant</a>
            </li>
            <li>
            <a href="#transpose">Task 7: Transpose</a>
            </li>
            <li>
            <a href="#eqsys">Task 8: Solving linear equation systems</a>
            </li>
            <li>
            <a href="#matmul">Task 9: Implementing matrix multiplication</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)

<article class="message task"><a class="anchor" id="diff"></a>
    <div class="message-header">
        <span>Task 1: Elementwise difference</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate $A-B$ in the code cell below.



</div></article>



In [6]:
# Task 1: Elementwise difference
elementwise_diff = A - B
print("Elementwise Difference (A - B):\n", elementwise_diff)

#To calculate the elementwise difference between matrices AA and BB, we simply subtract matrix BB from matrix AA.


Elementwise Difference (A - B):
 [[ 17.         -14.5         14.33333333 -12.75      ]
 [ 12.5        -10.66666667  10.25        -8.8       ]
 [  8.33333333  -6.75         6.2         -4.83333333]
 [  4.25        -2.8          2.16666667  -0.85714286]]


<article class="message task"><a class="anchor" id="mul_prop"></a>
    <div class="message-header">
        <span>Task 2: Multiplication properties</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate $AC$ and $CA$ in the code cell below. (You may use either [`np.dot`
](https://numpy.org/doc/stable/reference/generated/numpy.dot.html<elem-3>.dot)
 or the `@`
 operator).
2. Explain why the results are different.



</div></article>



In [8]:
# Task 2: Multiplication properties
AC = np.dot(A, C)  # Or A @ C
CA = np.dot(C, A)  # Or C @ A

print("Matrix AC:\n", AC)
print("Matrix CA:\n", CA)

# Matrix multiplication is not commutative, meaning ACAC is not necessarily equal to CACA. This is why the results differ.


Matrix AC:
 [[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]
Matrix CA:
 [[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]


<article class="message task"><a class="anchor" id="elem_mul"></a>
    <div class="message-header">
        <span>Task 3: Elementwise multiplication</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate the elementwise multiplication of $A$ and $C$ using the `*`
 operator.
2. Explain the difference between the `*`
 and `@`
 operators.



</div></article>



In [9]:
# Task 3: Elementwise multiplication

elementwise_mult = A * C
print("Elementwise Multiplication (A * C):\n", elementwise_mult)

# The * operator performs elementwise multiplication, whereas the @ or np.dot() operator performs matrix multiplication. They operate differently and give different results.

Elementwise Multiplication (A * C):
 [[1.         0.25       0.11111111 0.0625    ]
 [0.25       0.11111111 0.0625     0.04      ]
 [0.11111111 0.05       0.02857143 0.01851852]
 [0.0625     0.02857143 0.02083333 0.01587302]]


<article class="message task"><a class="anchor" id="inverses"></a>
    <div class="message-header">
        <span>Task 4: Inverses</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Use [`np.linalg.inv`
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
 to calculate  the inverse of $A$ and $C$.
2. Verify that $AA^{-1}=I$ and $CC^{-1}=I$. If the results differ from your expectations, argue why this is the case. _Hint: The question relates to the limitations of floating point numbers._



</div></article>



In [10]:
# Task 4: Inverses
A_inv = np.linalg.inv(A)
C_inv = np.linalg.inv(C)

# Verify
AA_inv = np.dot(A, A_inv)
CC_inv = np.dot(C, C_inv)

print("Matrix A * A_inv (should be identity):\n", AA_inv)
print("Matrix C * C_inv (should be identity):\n", CC_inv)

# Small numerical inaccuracies might occur due to the limitations of floating-point representation in computers, leading to results that are close to, but not exactly, the identity matrix.


Matrix A * A_inv (should be identity):
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  1.13686838e-13  0.00000000e+00]
 [ 3.55271368e-15 -5.68434189e-14  1.00000000e+00 -5.68434189e-14]
 [-1.06581410e-14  5.68434189e-14 -1.13686838e-13  1.00000000e+00]]
Matrix C * C_inv (should be identity):
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  2.84217094e-14]
 [ 0.00000000e+00 -2.27373675e-13  1.00000000e+00  5.68434189e-14]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


### Properties
<article class="message task"><a class="anchor" id="inverse_prop"></a>
    <div class="message-header">
        <span>Task 5: Inverse properties</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Use the code cell below to verify that:
1. $D^{-1}E^{-1} = (ED)^{-1}$
2. $D^{-1}E^{-1} \neq (DE)^{-1}$



</div></article>



In [11]:
# Task 5: Inverse properties
inverse_property_1 = np.dot(D_inv, E_inv)
inverse_property_2 = np.linalg.inv(np.dot(E, D))

print("D_inv * E_inv:\n", inverse_property_1)
print("(E * D)^-1:\n", inverse_property_2)

# D−1E−1 should be equal to (ED)−1(ED)−1, but D−1E−1D−1E−1 is not equal to (DE)−1(DE)−1 due to the non-commutative nature of matrix multiplication.

D_inv * E_inv:
 [[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
(E * D)^-1:
 [[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]


<article class="message task"><a class="anchor" id="determinant"></a>
    <div class="message-header">
        <span>Task 6: The determinant</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate the determinant of $A$, $B$, and $C$ using [`np.linalg.det`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html<elem-4>.linalg.det)
.
2. Based on the results, determine which of the matrices have an inverse.
3. Calculate the inverses of the matrices using [`np.linalg.inv`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html<elem-6>.linalg.inv)
. Explain what happens and how this is related to your answer in (2).



</div></article>



In [12]:
# Task 6: The determinant
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)

print("Determinant of A:", det_A)
print("Determinant of B:", det_B)
print("Determinant of C:", det_C)

# Determine invertibility
# A matrix is invertible if its determinant is not zero.
invertible_A = np.linalg.inv(A) if det_A != 0 else "Not Invertible"
invertible_B = np.linalg.inv(B) if det_B != 0 else "Not Invertible"
invertible_C = np.linalg.inv(C) if det_C != 0 else "Not Invertible"

print("Inverse of A:\n", invertible_A)
print("Inverse of B:\n", invertible_B)  # Should not be invertible
print("Inverse of C:\n", invertible_C)

# If the determinant of a matrix is zero, the matrix is singular (non-invertible).

Determinant of A: 1.6534391534390412e-07
Determinant of B: 0.0
Determinant of C: 1.0498026371034301e-07
Inverse of A:
 [[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
Inverse of B:
 Not Invertible
Inverse of C:
 [[   -72.           -225.            525.             42.        ]
 [  1260.           3675.          -8820.00000001   -630.        ]
 [ -3696.         -10710.00000001  25830.00000002   1764.        ]
 [  2700.           7830.00000001 -18900.00000001  -1260.        ]]


<article class="message task"><a class="anchor" id="transpose"></a>
    <div class="message-header">
        <span>Task 7: Transpose</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Verify that $(D^{-1})^\top$ and ${D^\top}^{-1}$ are equal.

<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">
  
  The transpose of a matrix `A`
 in Numpy can be calculated with `A.T`
.

  
  </div>
</article>



</div></article>



In [13]:
# Task 7: Transpose
D_inv_transpose = D_inv.T
D_transpose_inv = np.linalg.inv(D.T)

print("(D_inv)^T:\n", D_inv_transpose)
print("(D^T)^-1:\n", D_transpose_inv)


(D_inv)^T:
 [[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429  0.        ]
 [-0.33862434 -0.2010582   0.59259259]]
(D^T)^-1:
 [[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429 -0.        ]
 [-0.33862434 -0.2010582   0.59259259]]


## Linear equations
Matrices can represent systems of linear equations

$$
Ax=b
$$
where $A$ is the coefficient matrix, $x$ vector of unknowns, and $b$ is a vector of the dependent variables.
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$
<article class="message task"><a class="anchor" id="eqsys"></a>
    <div class="message-header">
        <span>Task 8: Solving linear equation systems</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


For each of the following sets of linear equations determine whether a unique solution exits. Recall that the determinant 
can be used to determine whether a matrix has an inverse:
a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$
b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$
c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$
d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$
e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$
f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$


</div></article>



In [14]:
# Task 8: Solving linear equation systems
# System a)
A1 = np.array([[2, 3], [1, 1]])
b1 = np.array([-1, 0])
x1 = np.linalg.solve(A1, b1)
print("Solution for system a):", x1)

# System b)
A2 = np.array([[1, 0], [0, 1]])
b2 = np.array([5, 7])
x2 = np.linalg.solve(A2, b2)
print("Solution for system b):", x2)

# System c)
A3 = np.array([[0, 1], [-2, -3]])
b3 = np.array([-1, 2])
x3 = np.linalg.solve(A3, b3)
print("Solution for system c):", x3)

# System d)
A4 = np.array([[1, -3, 3], [1, -5, 3], [4, -6, 6]])
b4 = np.array([0.5, 0.5, 1])
x4 = np.linalg.solve(A4, b4)
print("Solution for system d):", x4)

# System e)
A5 = np.array([[2, 3, 4], [1, 4, 1], [2, 5, 4]])
b5 = np.array([2, -2, 3])
x5 = np.linalg.solve(A5, b5)
print("Solution for system e):", x5)

# System f) - This system has no unique solution as the determinant will be zero
A6 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
b6 = np.array([2, -2, 3])

try:
    x6 = np.linalg.solve(A6, b6)
    print("Solution for system f):", x6)
except np.linalg.LinAlgError as e:
    print("System f) has no unique solution:", e)


Solution for system a): [ 1. -1.]
Solution for system b): [5. 7.]
Solution for system c): [ 0.5 -1. ]
Solution for system d): [ 0.         -0.          0.16666667]
Solution for system e): [-8.25  0.5   4.25]
System f) has no unique solution: Singular matrix


## Matrix multiplication
For an $N\times D$ matrix $A$ and a $D\times K$ matrix $B$, the 
matrix multiplication (or matrix product) is a new $N\times K$ matrix $R$. Elements $R_{ij}$ of $R$ can be calculated 
using the following formula

$$
R_{ij} = \sum_{d=1}^D A_{id}B_{dj}.
$$
In other words, it is the dot product of the $i$'th row vector of $A$ and the $j$'th column vector of $B$.
<article class="message task"><a class="anchor" id="matmul"></a>
    <div class="message-header">
        <span>Task 9: Implementing matrix multiplication <em>(optional)</em></span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


Implement matrix multiplication in the `matmul`
 function in the code cell below. You may use either Python lists or Numpy arrays, but the intention is to not use Numpy's built-in functions for matrix multiplication (i.e., `np.dot`
, `@`
, `np.matmul`
, etc.). You may, however, use `np.dot`
 for the purpose of computing the inner product between row and column vectors.
<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">
  
  It might be helpful to calculate the correct result by hand first, to make debugging easier.

  
  </div>
</article>



</div></article>



In [15]:
def matmul(a, b):
    # Get dimensions of matrices
    n = len(a)
    d = len(a[0])
    k = len(b[0])

    # Initialize result matrix with zeros
    result = np.zeros((n, k))

    # Perform matrix multiplication
    for i in range(n):
        for j in range(k):
            for l in range(d):
                result[i][j] += a[i][l] * b[l][j]
    return result

# Test matrices
ma = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

mb = [
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
]

# Perform matrix multiplication
result = matmul(ma, mb)
print("Result of matmul(ma, mb):\n", result)


Result of matmul(ma, mb):
 [[ 33.   6.  26.]
 [ 78.  21.  77.]
 [123.  36. 128.]]


This implementation manually computes the matrix product without relying on Numpy’s optimized functions.

That concludes the solution to the tasks. Each task has been addressed, and the relevant code has been provided.

---
